from __future__ import annotations
"""Repository protocol — defines the interface for vertical loop data access."""

from typing import List,  Optional

from typing import List,  Protocol, runtime_checkable
from uuid import UUID

from app.schemas.auth import UserDTO
from app.schemas.learning_path import LearningPath
from app.schemas.learning_record import LearningRecordCreate
from app.schemas.profile import StudentProfile
from app.schemas.recommendation import Recommendation
from app.schemas.resource import LearningResource, ResourceType
from app.schemas.workflow import AgentWorkflow


@runtime_checkable
class VerticalLoopRepositoryProtocol(Protocol):
    """Structural protocol for the vertical loop repository."""

    def get_user_by_username(self, username: str) -> Optional[UserDTO]: ...
    def get_default_user(self) -> UserDTO: ...
    def get_profile(self, user_id: UUID) -> Optional[StudentProfile]: ...
    def get_profile_by_id(self, profile_id: UUID) -> Optional[StudentProfile]: ...
    def get_profile_versions(self, user_id: UUID) -> List[StudentProfile]: ...
    def get_latest_profile_version(self, user_id: UUID) -> Optional[int]: ...
    def save_profile(self, profile: StudentProfile) -> StudentProfile: ...
    def snapshot_profile(self, user_id: UUID) -> StudentProfile: ...
    def save_profile_in_place(self, profile_id: UUID, profile: StudentProfile) -> StudentProfile: ...
    def merge_conversation_profile(self, conversation_profile_id: UUID, user_id: UUID) -> Optional[StudentProfile]: ...
    def create_path(self, user_id: UUID, goal: str, subject: str, base_agent_id: Optional[UUID] = None) -> LearningPath: ...
    def get_path(self, user_id: UUID) -> Optional[LearningPath]: ...
    def get_path_by_id(self, path_id: UUID, user_id: UUID) -> Optional[LearningPath]: ...
    def list_paths(self, user_id: UUID, page: int = 1, page_size: int = 20) -> tuple: ...
    def delete_path(self, path_id: UUID, user_id: UUID) -> bool: ...
    def complete_path_node(self, user_id: UUID, node_id: UUID) -> Optional[LearningPath]: ...
    def create_workflow(self, user_id: UUID, input_payload: Optional[dict] = None, emit_progress=None) -> AgentWorkflow: ...
    def get_workflow(self, workflow_id: UUID) -> Optional[AgentWorkflow]: ...
    def create_resource(self, user_id: UUID, knowledge_point: str, resource_type: ResourceType, difficulty: str, base_agent_id: Optional[UUID] = None, conversation_id: Optional[UUID] = None) -> LearningResource: ...
    def get_resource(self, resource_id: UUID) -> Optional[LearningResource]: ...
    def create_recommendations(self, user_id: UUID) -> List[Recommendation]: ...
    def get_recommendations(self, user_id: UUID) -> List[Recommendation]: ...
    def save_learning_record(self, record: LearningRecordCreate) -> Optional[UUID]: ...
    def list_learning_records(self, user_id: UUID) -> List[dict]: ...
    def list_questions(self, knowledge_point: Optional[str] = None, question_type: Optional[str] = None, subject: Optional[str] = None, difficulty: Optional[str] = None) -> List[dict]: ...
    def get_question(self, question_id: UUID) -> Optional[dict]: ...
    def save_question(self, data: dict) -> dict: ...
    def delete_question(self, question_id: UUID) -> bool: ...
    def save_answer_record(self, data: dict) -> dict: ...
    def get_user_answer_history(self, user_id: UUID, question_id: Optional[UUID] = None) -> List[dict]: ...
    def list_user_resources(self, user_id: UUID) -> List[dict]: ...
    def delete_resource(self, user_id: UUID, resource_id: UUID) -> bool: ...
    def emit_event(self, user_id: UUID, event_type: str, event_payload: dict, confidence: float, source_type: str = "agent", source_id: Optional[UUID] = None) -> UUID: ...
    def list_pending_events(self, user_id: UUID, limit: int = 20) -> List[dict]: ...
    def update_event_status(self, event_id: UUID, status: str, error_message: Optional[str] = None) -> None: ...
    def save_profile_and_update_event(self, profile: StudentProfile, event_id: UUID, event_status: str = "applied", error_message: Optional[str] = None) -> StudentProfile: ...
    def save_assessment_snapshot(self, user_id: UUID, data: dict) -> dict: ...
    def list_assessment_history(self, user_id: UUID, limit: int = 20) -> List[dict]: ...
